library(tm)
library(caret)
library(RWeka)
setwd("C:/Users/schinnamgar/Desktop/Final research/execute")
set.seed(123)
svmBag$fit <- function (x, y, ...) 
{
  library(kernlab)
  out <- ksvm(as.matrix(x), y, prob.model = is.factor(y),kernel="vanilladot",...)
  out
}
for(iter in 1:10)
{
datasetname <- paste("dataset",iter,".csv",sep="")
dataset_raw_name <- paste("dataset",iter,"-","raw",".","csv",sep="")
dataset_chi_name <- paste("dataset",iter,"-","chi",".","arff",sep="")
dataset_metrics_name <- paste("SVMbagging-classification","-","dataset",iter,"-","chi","-","metrics",".","csv",sep="")
dataset_predictions_name <- paste("SVMbagging-classification","-","dataset",iter,"-","chi","-","predictions",".","csv",sep="")  
if(file.exists(dataset_metrics_name) | file.exists(dataset_predictions_name))
{
  file.remove(dataset_metrics_name)
  file.remove(dataset_predictions_name)
}
orig_dataset <- read.csv(datasetname)
orig_dtmdataset <- read.csv(dataset_raw_name)
temp <- cbind("Original Dimensions","")
write.table(temp,dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F,row.names=F)
dimensions <- cbind(dim(orig_dtmdataset)[1],(dim(orig_dtmdataset)[2]-1))
write.table(dimensions,dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F,row.names=F)
dataset <- read.arff(dataset_chi_name)
temp <- cbind("chi filtered Dimensions","")
write.table(temp,dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F,row.names=F)
dimensions <- cbind(dim(dataset)[1],(dim(dataset)[2]-1))
write.table(dimensions,dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F,row.names=F)
bagctrl <- bagControl(fit = svmBag$fit,predict = svmBag$pred,aggregate = svmBag$aggregate)
ctrl <- trainControl(method = "cv", number = 10,savePred = T)
model <- train(zclass ~ ., data = dataset,"bag", trControl = ctrl,bagControl = bagctrl)
modelpred <- model$pred
write.csv(modelpred,dataset_predictions_name,na="0")
library(mlearning)
library(Metrics)
results <- read.csv(dataset_predictions_name)
mean_abs_err <- mae(as.numeric(results$pred),as.numeric(results$obs))
results$obs <- factor(results$obs)
results$pred <- factor(results$pred,levels=c(levels(results$obs)))
mean_abs_err <- mae(as.numeric(results$pred),as.numeric(results$obs))
results$pred <- factor(results$pred,levels=c(levels(results$obs)))
confusiontable <-confusionMatrix(results$pred,results$obs)
write.table(confusiontable$overall[1],dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F)
write.table(confusiontable$overall[2],dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F)
calFscore <- confusion(as.factor(as.numeric(results$pred)),as.factor(as.numeric(results$obs)))
summary_fscore <- summary(calFscore, type = c("Fscore", "Recall", "Precision"))
temp <- cbind("FScore",mean(summary_fscore$Fscore))
write.table(temp,dataset_metrics_name,append=T,sep=",",row.names=F,col.names=F,,eol = "\n")
temp <- cbind("Mean Absolute Error",mean_abs_err)
write.table(temp,dataset_metrics_name,append=T,sep=",",row.names=F,col.names=F,eol = "\n")
rm(list=setdiff(ls(), "iter"))
}