library(caret)
library(foreign)
library(nnet)
library(C50)
library(e1071)
setwd("C:/Users/schinnamgar/Desktop/Final research/execute")
set.seed(123)
for(iter in 1:10)
{
  datasetname <- paste("dataset",iter,".csv",sep="")
  dataset_raw_name <- paste("dataset",iter,"-","raw",".","csv",sep="")
  dataset_chi_name <- paste("dataset",iter,"-","chi",".","arff",sep="")
  dataset_testdatapredictions_name <- paste("stackingc50nnetsvm-testdata","-","dataset",iter,"-","chi","-","predictions",".","csv",sep="")  
  dataset_trainingdatapredictions_name <- paste("stackingc50nnetsvm-trainingdata","-","dataset",iter,"-","chi","-","predictions",".","csv",sep="")  
  dataset_finalpredictions_train_name <- paste("stackingc50nnetsvm-predictions","-","dataset",iter,"-","chi","-","svmmetaclassifier",".","csv",sep="") 
  dataset_metrics_name <- paste("stackingc50nnetsvm-metrics","-","dataset",iter,"-","chi","-","c50metaclassifier",".","csv",sep="") 
  dataset_predictions_name <- paste("stackingc50nnetsvm-predictions","-","dataset",iter,"-","chi","-","c50metaclassifier",".","csv",sep="")
  if(file.exists(dataset_predictions_name))
    file.remove(dataset_predictions_name)
  if(file.exists(dataset_metrics_name))
    file.remove(dataset_metrics_name)
  dataset <- read.arff(dataset_chi_name)
  predictors <- read.csv(dataset_trainingdatapredictions_name,header=F)
  testpredictors <- read.csv(dataset_testdatapredictions_name,header=F)
  predictors$zclass <- dataset$zclass
  model <- train(zclass ~ ., data = predictors, method = "C5.0")
  finalpredictions <- predict(model, testpredictors)
  finalpredictions <- data.frame(finalpredictions)
  colnames(finalpredictions)[1] <- "pred"
  finalpredictions$obs <- predictors$zclass
  write.csv(finalpredictions,dataset_predictions_name,na="0")
  library(mlearning)
  library(Metrics)
  results <- read.csv(dataset_predictions_name)
  mean_abs_err <- mae(as.numeric(results$pred),as.numeric(results$obs))
  results$obs <- factor(results$obs)
  results$pred <- factor(results$pred,levels=c(levels(results$obs)))
  mean_abs_err <- mae(as.numeric(results$pred),as.numeric(results$obs))
  results$pred <- factor(results$pred,levels=c(levels(results$obs)))
  confusiontable <-confusionMatrix(results$pred,results$obs)
  write.table(confusiontable$overall[1],dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F)
  write.table(confusiontable$overall[2],dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F)
  calFscore <- confusion(as.factor(as.numeric(results$pred)),as.factor(as.numeric(results$obs)))
  summary_fscore <- summary(calFscore, type = c("Fscore", "Recall", "Precision"))
  temp <- cbind("FScore",mean(summary_fscore$Fscore))
  write.table(temp,dataset_metrics_name,append=T,sep=",",row.names=F,col.names=F,,eol = "\n")
  temp <- cbind("Mean Absolute Error",mean_abs_err)
  write.table(temp,dataset_metrics_name,append=T,sep=",",row.names=F,col.names=F,eol = "\n")
}