library(tm)
library(caret)
setwd("C:/Users/schinnamgar/Desktop/Final research/Short answers/Data")
set.seed(123)
for(iter in 1:10)
{
  for (num in c(0.90,0.92,0.94,0.96,0.98))
  {
datasetname <- paste("dataset",iter,".csv",sep="")
dataset_raw_name <- paste("dataset",iter,"-","raw",".","csv",sep="")
dataset_pca_name <- paste("dataset",iter,"-","pca-",num,".","csv",sep="")
dataset_metrics_name <- paste("c50-classification","-","dataset",iter,"-","pca",num,"-","metrics",".","csv",sep="")
dataset_predictions_name <- paste("c50-classification","-","dataset",iter,"-","pca",num,"-","predictions",".","csv",sep="")  
if(file.exists(dataset_metrics_name) | file.exists(dataset_predictions_name))
{
  file.remove(dataset_metrics_name)
  file.remove(dataset_predictions_name)
}
orig_dataset <- read.csv(datasetname)
orig_dtmdataset <- read.csv(dataset_raw_name)
temp <- cbind("Original Dimensions","")
write.table(temp,dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F,row.names=F)
dimensions <- cbind(dim(orig_dtmdataset)[1],(dim(orig_dtmdataset)[2]-1))
write.table(dimensions,dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F,row.names=F)
dataset <- read.csv(dataset_pca_name)
temp <- cbind("pca filtered Dimensions","")
write.table(temp,dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F,row.names=F)
dimensions <- cbind(dim(dataset)[1],dim(dataset)[2])
write.table(dimensions,dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F,row.names=F)
dataset$class <- as.factor(orig_dataset[,2])
ctrl <- trainControl(method = "cv", number = 10,savePred = T)
model <- train(class ~ ., data = dataset, method = "C5.0", trControl = ctrl)
trialsvalue<-as.numeric(model$bestTune[1])
modelvalue <- as.character(model$bestTune[2])
modelvalue <- as.factor(modelvalue)
winnowvalue <- as.logical(model$bestTune[3])
modelpred <- model$pred
levels(modelvalue) <- levels(modelpred$model)
modelpred <- subset(modelpred,trials==trialsvalue & winnow==winnowvalue & model==modelvalue)
write.csv(modelpred,dataset_predictions_name,na="0")
library(mlearning)
library(Metrics)
results <- read.csv(dataset_predictions_name)
mean_abs_err <- mae(as.numeric(results$pred),as.numeric(results$obs))
results$obs <- factor(results$obs)
results$pred <- factor(results$pred,levels=c(levels(results$obs)))
mean_abs_err <- mae(as.numeric(results$pred),as.numeric(results$obs))
results$pred <- factor(results$pred,levels=c(levels(results$obs)))
confusiontable <-confusionMatrix(results$pred,results$obs)
write.table(confusiontable$overall[1],dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F)
write.table(confusiontable$overall[2],dataset_metrics_name,append=T,sep=",",eol = "\n",col.names=F)
calFscore <- confusion(as.factor(as.numeric(results$pred)),as.factor(as.numeric(results$obs)))
summary_fscore <- summary(calFscore, type = c("Fscore", "Recall", "Precision"))
temp <- cbind("FScore",mean(summary_fscore$Fscore))
write.table(temp,dataset_metrics_name,append=T,sep=",",row.names=F,col.names=F,,eol = "\n")
temp <- cbind("Mean Absolute Error",mean_abs_err)
write.table(temp,dataset_metrics_name,append=T,sep=",",row.names=F,col.names=F,eol = "\n")
}
}